name: popgenToolkit
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python
  - numpy
  - pandas
  - scipy
  - matplotlib
  - statsmodels
  - seaborn
  - tqdm
  - pysam
  - biopython
  - intervaltree
  - snakemake>=8.0.0
  - snakemake-executor-plugin-cluster-generic
